### ISSUE TITLE
Hi,i haven't this Pica.glb scene model,so i get the black fullscreen 

### ISSUE THREAD

**Issue by jlk1997** [RMichelsen/VulkanHybridRenderer#1]
How can i fix it?
![image](https://github.com/RMichelsen/VulkanHybridRenderer/assets/56379549/0b6205fc-f275-4a3b-a303-d0d41b4d0adc)

**Comment by jlk1997** [comment]
![image](https://github.com/RMichelsen/VulkanHybridRenderer/assets/56379549/6a2172db-b14a-4aa6-93b8-b0d2693903e5)

**Comment by jlk1997** [comment]
after i build a model folder,its still a back background
![image](https://github.com/RMichelsen/VulkanHybridRenderer/assets/56379549/99cc7409-8689-48b4-8afe-7836298d6a89)

**Comment by RMichelsen** [comment]
Hi, this project is not meant to work out of the box and is mostly meant as a code reference if someone is interested in a hybrid renderer in Vulkan.

That said, you are missing a `.glb` or `.gltf` file to load from. You can find the PICA scene here: https://sketchfab.com/3d-models/pica-pica-mini-diorama-01-45e26a4ea7874c15b91bd659e656e30d - the renderer should work with any `.glb` or `.gltf` scene though.

**Comment by jlk1997** [comment]
My graduate study is hybrid rendering, what should I learn to understand your project

**Comment by jlk1997** [comment]
Are there any papers for reference in this project？

**Comment by jlk1997** [comment]
after i add this model.it is still a full black，how  can i fix it
![image](https://github.com/RMichelsen/VulkanHybridRenderer/assets/56379549/68c05a80-7fe7-476e-90c4-8d91039be443)
